Import Debian changes 2.42.10+dfsg-1+deb12u3
gdk-pixbuf (2.42.10+dfsg-1+deb12u3) bookworm; urgency=medium
.
  * Team upload.
.
  [ Jeremy Bícha ]
  * debian/gbp.conf: Branch for bookworm.
.
  [ Carlos Henrique Lima Melara ]
  * debian/patches/CVE-2025-7345.patch: import patch from upstream.
      - CVE-2025-7345: A flaw exists in gdk‑pixbuf within the
        gdk_pixbuf__jpeg_image_load_increment function (io-jpeg.c) and in
        glib’s g_base64_encode_step (glib/gbase64.c) potentially leading to a
        buffer overflow. (Closes: #1109262)
  * debian/salsa-ci.yml: build with nocheck and pass SALSA_CI=true for
    autopkgtest job.
  * debian/tests/installed-tests{,flaky}: check SALSA_CI variable to decide
    what is flaky or not.

diff --git a/debian/tests/installed-tests-flaky b/debian/tests/installed-tests-flaky
--- a/debian/tests/installed-tests-flaky
+++ b/debian/tests/installed-tests-flaky
@@ -1,9 +1,19 @@
 #!/bin/sh
 
-set -eu
+set -e
 
+if [ -n "$SALSA_CI" ]; then
+    # pixbuf-fail triggers oom-killer in salsa-ci
+    flaky_tests="gdk-pixbuf/pixbuf-randomly-modified.test \
+            gdk-pixbuf/pixbuf-fail.test"
+else
+    flaky_tests="gdk-pixbuf/pixbuf-randomly-modified.test"
+fi
+
+# Deliberately word-splitting:
+# shellcheck disable=SC2086
 exec gnome-desktop-testing-runner \
 --report-directory="$AUTOPKGTEST_ARTIFACTS" \
 --tap \
-gdk-pixbuf/pixbuf-randomly-modified.test \
+$flaky_tests \
 ${NULL+}
